/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RCALCULADORA_H_RPCGEN
#define _RCALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum calculadorastat {
	CALCULADORA_OK = 0,
	CALCULADORA_NOK = 1,
};
typedef enum calculadorastat calculadorastat;

struct resultado {
	calculadorastat status;
	union {
		float respuesta;
	} resultado_u;
};
typedef struct resultado resultado;

#define CALCULADORA_PROGRAM 0x3
#define CALCULADORA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define BASIC 1
extern  resultado * basic_1(void *, CLIENT *);
extern  resultado * basic_1_svc(void *, struct svc_req *);
extern int calculadora_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BASIC 1
extern  resultado * basic_1();
extern  resultado * basic_1_svc();
extern int calculadora_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calculadorastat (XDR *, calculadorastat*);
extern  bool_t xdr_resultado (XDR *, resultado*);

#else /* K&R C */
extern bool_t xdr_calculadorastat ();
extern bool_t xdr_resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RCALCULADORA_H_RPCGEN */
