/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rcalculadora.h"

bool_t
xdr_calculadorastat (XDR *xdrs, calculadorastat *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado (XDR *xdrs, resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_calculadorastat (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case CALCULADORA_OK:
		 if (!xdr_float (xdrs, &objp->resultado_u.respuesta))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
